### ISSUE TITLE
Q: Should you need any help with this just lmk ;)

### ISSUE THREAD

**Issue by vexy** [mijovic/betdapp#1]
...looks like a nice idea

**Comment by mijovic** [comment]
It is a small project from hackathon. I plan to continue working on it.

If you want to help it would be great :)

**Comment by vexy** [comment]
I'm all yours boss ☺️

**Comment by mijovic** [comment]
@vexy Sorry, I was a bit busy last two weeks. When it would be good time for you to jump on a call about this project?
